version: '3'

services:
  flask:
    build: 
      context: flask
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql_config:/etc/mysql/conf.d

 postfix:
    image: boky/postfix
    container_name: postfix
    ports:
      - "25:25"
    environment:
      # Environment variables for Postfix
      POSTFIX_myhostname: zomby.live
    volumes:
      - postfix-data:/var/spool/postfix
      - postfix-log:/var/log/postfix

  dovecot:
    image: instrumentisto/dovecot
    container_name: dovecot
    ports:
      - "993:993" # IMAP over SSL
    volumes:
      - dovecot-data:/var/mail
      - dovecot-config:/etc/dovecot
    depends_on:
      - postfix

volumes:
  dbdata:
  postfix-data:
  postfix-log:
  dovecot-data:
  dovecot-config:
