version: '3'

services:
  flask:
    build: 
      context: .
      dockerfile: flask/Dockerfile
    container_name: flask
    ports:
      - "5000:5000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask
