version: '3'

services:
  flask:
    build: 
      context: flask
      dockerfile: Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'fraser'
      MYSQL_PASSWORD: 'QJhD:NdfS7E-Uz6q<xsX'
      MYSQL_ROOT_PASSWORD: 'U;PR`AFqW<K(GvZm7pYgzx'
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql_config:/etc/mysql/conf.d

  postfix:
    image: boky/postfix
    container_name: postfix
    ports:
      - "25:25"
    environment:
      POSTFIX_myhostname: zomby.live
      ALLOWED_SENDER_DOMAINS: "zomby.live"
    volumes:
      - postfix-data:/var/spool/postfix
      - postfix-log:/var/log/postfix

  dovecot:
    image: dovecot/dovecot
    volumes:
      - dovecot-mail:/var/mail
      - ./dovecot/dovecot-config/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./dovecot/dovecot-config/10-auth.conf:/etc/dovecot/conf.d/10-auth.conf
      - ./dovecot/dovecot-config/10-mail.conf:/etc/dovecot/conf.d/10-mail.conf
      - ./dovecot/dovecot-config/10-ssl.conf:/etc/dovecot/conf.d/10-ssl.conf

volumes:
  dbdata:
  postfix-data:
  postfix-log:
  dovecot-data:
  dovecot-config:
